- name: Deploy Calculator Container
  hosts: local

  tasks:
    - name: Stop old container
      command: docker stop scientific-calculator
      ignore_errors: yes

    - name: Remove old container
      command: docker rm scientific-calculator
      ignore_errors: yes

    - name: Pull latest Docker image
      command: docker pull key717/scientific-calculator:latest

    - name: Run calculator container
      command: docker run -d -it --name scientific-calculator key717/scientific-calculator:latest
